# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a914123fb839d4cc478b001812feb74f0df86be66d48e8e016008f54e1204c317745f89f9b204e550e93f4bb25e0365743089a5892acb5580ebc87306ce3ce8

test:
  secret_key_base: f3d1e0c5687372ba8d9eac2a9df2110db96c0b046d2c7d3b8de613d7a19e985e7735c2f004f19c2152f241b247e05df9f17cdea4794d0c0d20e50a3286f2b827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
